### ISSUE TITLE
Document zeroc-ice build

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble-releng-experimental#1] opened 2020-03-17 15:54 UTC
> As far as progress, I made changes that would allow the use of forks of vcpkg and ice that davidebeatrici and I worked on.
> ZeroC did not approve the pull request to add cmake to the 3.7 branch. They are planning an overhaul of their build system for 4.0 and this seemed like the most productive way to not lose the work I've done, yet not complicate work they may be doing. There is also no guarantee they will use cmake as they are only considering it at this time.

**Comment by ghost** [comment] 2020-03-18 02:19
@Kissaki - is there a preferred script type that should be used for Windows? I could provide a powershell script specifically for Windows that gets the dependencies and builds mumble. `git-bash` was selected for getting dependencies, because people who use git for Windows already have it and it removes the need to write different scripts for different platforms. It was also a WIP until a more in-depth discussion could be had about goals. It seems like the time to have that discussion has come. :)

**Comment by Kissaki** [comment] 2020-03-18 15:28
I don’t have a clear candidate.

Microsoft seems to advocate Powershell, and try to move towards it. But for simple scripts batch still seems easier and more compatible (no version specific stuff). But the syntax is not the best either.

Last time I tried with this repo I had a mixture of both, trying both out, and succeeding with only one. Right now I have bat scripts.

I also thought about creating a small app/.NET App. This could potentially provide easier and better integration and features, and if so in a much superior code (structure, readability and robustness/clarity/type-safety). This one could call individual scripts of course.

Having (a bunch of scripts) and parameters is not really user and new contributor friendly. An app, with guided command line or useful GUI could improve this experience a lot.

**Comment by Kissaki** [comment] 2020-03-18 16:08
If sufficient I would probably prefer batch over pwsh unless a good advantage is presented.

**Comment by ghost** [comment] 2020-03-18 16:14
The only advantage worth noting is the use of PS core which is OSS and works on Linux and macOS. It would be an additional dependency, though.

https://github.com/PowerShell/PowerShell/releases

**Comment by ghost** [comment] 2020-03-20 18:54
I am going to look into adding vcpkg as a submodule so the scripting requirements can be reduced. We could also look at something like this for our pipelines:

https://github.com/lukka/CppBuildTasks

**Comment by ghost** [comment] 2020-03-24 23:37
Client server builds can be initiated together or separately with the following bools:

```
-Dclient=ON/OFF
-Dserver=ON/OFF
```

Default is `ON`

**Comment by Kissaki** [comment] 2020-03-26 21:42
> 
> 
> Client server builds can be initiated together or separately with the following bools:
> 
> ```
> -Dclient=ON/OFF
> -Dserver=ON/OFF
> ```
> 
> Default is `ON`

Are you talking about Ice or Mumble here?

**Comment by ghost** [comment] 2020-03-26 22:43
> > Client server builds can be initiated together or separately with the following bools:
> > ```
> > -Dclient=ON/OFF
> > -Dserver=ON/OFF
> > ```
> > 
> > 
> > Default is `ON`
> 
> Are you talking about Ice or Mumble here?

This is in reference to Mumble. The Milestone was attached to this issue. I believe the last of the Ice build testing has been done.

**Comment by ghost** [comment] 2020-08-13 05:54
@Kissaki I would say that this issue could probably be resolved since the cmake PR has been merged and the documentation has been completed. There was some cross talk regarding the script flavor that should be used on Windows and that should probably be in a new issue going forward.

**Comment by Kissaki** [comment] 2020-08-14 16:30
How was it or should this be resolved then? I feel like I am missing some context?

**Comment by ghost** [comment] 2020-08-17 06:47
Maybe the title needs to be updated then. The zeroc-ice reference is misleading. Since the ability to build client and server is part of the config step of the cmake project by design, that would mean the only milestone left is for replacement of git-bash if that is still a goal.

**Comment by ghost** [comment] 2020-08-21 03:41
@davidebeatrici, I suggest if you are still interested in moving the "Build' documentation section to the main repo then we should make use of this issue. Do you just want to add it to the main README?

**Comment by davidebeatrici** [comment] 2020-08-21 22:08
I'm not sure. Maybe we should create a dedicated file, something like `BUILD.md`.

**Comment by Kissaki** [comment] 2020-08-22 09:34
We should not put everything in the README. We have so much stuff that it makes sense to split it up. It shouldn’t be so long that overview, readability and discoverability goes over board. This repository’s README is already max length of what I would deem reasonable.

**Comment by Krzmbrzl** [comment] 2020-09-06 09:34
I will close this issue as the original topic seems to be resolved and the integration into the main repo will be done by me shortly. And I'll put the build instructions in a separate file / directory.

**Closed as completed by Krzmbrzl** 2020-09-06 09:34 UTC
