### ISSUE TITLE
[Discussion] - Create script for Windows to replace bash script requirement

### ISSUE THREAD

**Issue by ghost** [mumble-voip/mumble-releng-experimental#9] opened 2020-08-21 03:09 UTC
PowerShell and batch scripts were suggested for Windows instead of `git-bash` so a discussion should be had about which would be a better choice. The current best option is a `cmd` based script due to the Visual Studio Development cmd requirement and the PowerShell version only supporting x86.

**Comment by ghost** [comment] 2020-08-22 23:41
Testing on hold due to https://github.com/mumble-voip/mumble-releng-vcpkg/issues/10

**Comment by Kissaki** [comment] 2020-08-23 08:10
You say it should be discussed but also say what the best option is? :D

Personally I find neither intuitive. When I implement small scripts I typically come back to batch because I find powershell not intuitive (and familiar) enough. But of course batch syntax is awful for logic functionality, and is missing some functionality we may miss here (like downloading files)?

**Comment by ghost** [comment] 2020-08-23 08:17
I brought up batch as a more familiar or least intrusive because powershell will require setting the execution policy. It seemed like the best option at the time. `if` statements didn't really cooperate so I abandoned it. The powershell version is "done" but I'm holding off on confirming that. It sounds like we should explore a better option. I recall a discussion about making a gui app for it. That could be helpful especially if people want to update the vcpkg repo locally.

**Comment by ghost** [comment] 2020-08-29 01:47
I have pushed a powershell script that I have tested as working. The readme has also been updated. This is working on Windows 10 and may work on Server or CI.

**Comment by Krzmbrzl** [comment] 2020-08-31 17:52
The script also works on Windows 7 (with some adjustments necessary inside vcpkg to circumvent TLS 1.3 issues - which are documented now in case someone else is also still using Win7 ^^)

I think having a powershell script for windows users is a lot better than having them to run bash scripts. Given that Powershell is the more modern way of using windows (kinda), I think I do indeed perfer it over a batch script.

**Comment by ghost** [comment] 2020-08-31 21:16
> The script also works on Windows 7 (with some adjustments necessary inside vcpkg to circumvent TLS 1.3 issues - which are documented now in case someone else is also still using Win7 ^^)

As thoughtful as that is, I would consider it secondary. People should no longer be using Windows 7/2008 R2 since Microsoft is no longer supporting it without purchasing Extended Support. Could you add a blurb in the documentation that highlights that? 

I don't think there are enough differences in what we are doing now versus any of the requirements needed in Windows 7 that warrants us going above and beyond for Extended Support users. I do know that Qt will eventually stop supporting Windows 7 so we may want to keep an eye on that. This would make 1.4 an unlikely option in the very near future for those who are Extended Support users given vcpkg will install the current Qt LTS under the new build instructions. At some point, they would have to build their own development environment and toolchain, and forego vcpkg entirely.

> I think having a powershell script for windows users is a lot better than having them to run bash scripts. Given that Powershell is the more modern way of using windows (kinda), I think I do indeed perfer it over a batch script.

I agree. There is more of a logical flow to the scripting versus using `cmd`. My only displeasure about it is they don't make a 64 bit Developer Powershell.

**Comment by Krzmbrzl** [comment] 2020-09-01 06:41
I don't think it is our duty to warn Win7 users. I also didn't include exclusive instructions for Win7. I only added an entry for a given error message and what it could be the cause and how to fix/circumvent it. I also mentioned that this for instance can happen on Win7 installs. I don't see anything wrong with that 🤷

**Comment by ghost** [comment] 2020-09-01 13:54
I was thinking more along the lines of a clear cut off date that Qt will stop supporting Windows 7. Thus, so will we.

**Comment by Krzmbrzl** [comment] 2020-09-01 14:38
Yeah I'm fine with that as soon as it will actually stop working. As long as it only requires minor tweaks though, I'd continue to document them (provided that all minor tweaks together won't end up in pages of documentation on their own xD)
This will obviously be no priority but since I'll have to figure this stuff out for myself every now and then, I might as well write them down ^^

**Comment by ghost** [comment] 2020-09-01 16:11
@Krzmbrzl - Definitely trying to avoid that.Unless @Kissaki objects, we could probably close this and mark the milestone complete.

**Comment by Krzmbrzl** [comment] 2020-09-01 16:42
> Definitely trying to avoid that

"that" == a huge pile of Win7 instructions
or
"that" == Documenting troubleshooting issues that (also) occur on Win7, in general
?

**Comment by ghost** [comment] 2020-09-01 16:51
> "that" == a huge pile of Win7 instructions

**Comment by Kissaki** [comment] 2020-09-05 14:30
I agree. Win 7 docs should be secondary and not negatively impact the mainline docs. Aside docs are fine. If it's too much it may make sense to put them into a separate file.

I haven’t tested the script yet but otherwise, if it works, I do not see why we should keep this ticket open. If a first running version is done as planned/requested that's that. We can use this as baseline then and create new tickets for bugs and extensions.

Thought/Aside: Maybe I can try the script out later.

**Comment by Krzmbrzl** [comment] 2020-09-06 09:31
The script was working fine for me. Thus I'll close this issue until someone finds out that it doesn't work for them

**Closed as completed by Krzmbrzl** 2020-09-06 09:31 UTC
